spring.cache.cache-names=schedules
spring.cache.caffeine.spec=maximumSize=52,expireAfterWrite=1h

# MongoDB Connection
spring.mongodb.host=localhost
spring.mongodb.port=27010
spring.mongodb.database=schedule_bridge
spring.mongodb.authentication-database=admin
spring.mongodb.username=test
spring.mongodb.password=test